/*
Problem: Find the Difference

Description:
You are given two strings s and t.
String t is generated by shuffling s and adding one extra character.
Return the extra character.

Approach:
1. XOR all characters of s and t.
2. Same letters cancel out; the extra one remains.

Time: O(n)
Space: O(1)
*/

#include <stdio.h>

// Function to find extra character
char findTheDifference(char* s, char* t) {
    char res = 0;
    while (*s) {
        res ^= *s;
        s++;
    }
    while (*t) {
        res ^= *t;
        t++;
    }
    return res;
}

// Test
int main() {
    char s[] = "abcd";
    char t[] = "abcde";

    char result = findTheDifference(s, t);
    printf("The added character is: %c\n", result);

    return 0;
}

/*
========= OUTPUT =========
The added character is: e
==========================
*/
